= Example for Gwen with JUnit

== About

This show an example on how to integrate https://github.com/shazam/gwen[Gwen^]
with http://arquillian.org/modules/graphene-extension/[Arquillian Graphene^]

This example will start a local browser and will run some tests on a web site.

== Features

The following features are shown in this example (see `StartPageFeature.java`):

. you find all test steps in the page objects

== How to run from command line and continuous integration

Install maven and run as follows:

   mvn clean test
   mvn surefire-report:report-only

This will download http://phantomjs.org/[Phantom^] to run headless browser tests and run the tests using the `arquillian-headless.xml` settings.

To look at the results, open the folder `target/site/surefire-report.html`.

== How to run from your IDE

According to `arquillian.xml` interactive tests will use a locally running Selenium server that will forward requests to a locally installed instance of Firefox.

Preparation:

  . ensure that Firefox is installed on the local machine
  . follow the instructions in `selenium/README-selenium.md` to download the most recent
    selenium JAR file
  . start `selenium/selenium.bat`

Running a Unit test from your IDE:

  . run `StartPageFeature.java` like you would run any other unit test.

